#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 27 10:02:09 2018

@author: obarquero
"""

import numpy as np

m = np.load('best_model.npy')

best_model = m.item()
best_model = best_model['best_model']